# Generated by Django 4.1.7 on 2023-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='simage',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
