# Generated by Django 4.1.7 on 2023-03-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_simage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='simage',
            field=models.ImageField(blank=True, default='media/pics/2.jpg', null=True, upload_to='pics'),
        ),
    ]
